-- ============================================================================
-- OJA baseline, chunk 01 of 08: Extensions and enum types
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 17-30).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 1. EXTENSIONS AND ENUM TYPES
-- ============================================================================

create extension if not exists pgcrypto;          -- gives us gen_random_uuid()

-- Enums model a CLOSED domain: only these values can ever exist in the column.
-- This is a constraint enforced by the engine, not by application code.
create type user_role      as enum ('owner', 'manager', 'staff');
create type movement_type  as enum ('in', 'out', 'adjustment');
create type sale_status    as enum ('draft', 'completed', 'void');
create type payment_method as enum ('cash', 'transfer', 'card', 'credit');

