-- ============================================================================
-- OJA baseline, chunk 02 of 08: Core tables, constraints and indexes
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 31-195).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 2. CORE TABLES
-- ============================================================================

-- ---------------------------------------------------------------- tenants --
create table organisations (
    id          uuid primary key default gen_random_uuid(),
    name        text        not null check (length(trim(name)) > 0),
    slug        text        not null unique,       -- URL-safe identifier
    currency    char(3)     not null default 'NGN',
    low_stock_default integer not null default 5 check (low_stock_default >= 0),
    created_at  timestamptz not null default now()
);

comment on table organisations is
    'Tenant root. Every other table hangs off this so data can be isolated.';


-- ------------------------------------------------------------- app users --
-- profiles.id is BOTH the primary key AND a foreign key to Supabase's
-- auth.users table. This is a one-to-one relationship: one login, one profile.
create table profiles (
    id          uuid primary key references auth.users(id) on delete cascade,
    org_id      uuid        not null references organisations(id) on delete cascade,
    full_name   text        not null,
    email       text        not null,
    role        user_role   not null default 'staff',
    is_active   boolean     not null default true,
    created_at  timestamptz not null default now()
);

create index idx_profiles_org on profiles(org_id);


-- ------------------------------------------------------------ categories --
create table categories (
    id          uuid primary key default gen_random_uuid(),
    org_id      uuid        not null references organisations(id) on delete cascade,
    name        text        not null check (length(trim(name)) > 0),
    created_at  timestamptz not null default now(),
    -- A category name must be unique INSIDE an organisation, not globally.
    -- Two different shops may both have a category called "Drinks".
    constraint uq_category_per_org unique (org_id, name)
);

create index idx_categories_org on categories(org_id);


-- -------------------------------------------------------------- products --
create table products (
    id             uuid primary key default gen_random_uuid(),
    org_id         uuid        not null references organisations(id) on delete cascade,
    category_id    uuid        references categories(id) on delete restrict,
    sku            text        not null,
    name           text        not null check (length(trim(name)) > 0),
    unit_price     numeric(12,2) not null check (unit_price >= 0),  -- CURRENT selling price
    cost_price     numeric(12,2) not null default 0 check (cost_price >= 0),
    reorder_level  integer     not null default 5 check (reorder_level >= 0),
    is_active      boolean     not null default true,   -- soft delete
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    constraint uq_sku_per_org unique (org_id, sku)
);

create index idx_products_org      on products(org_id);
create index idx_products_category on products(category_id);
-- Case-insensitive search on product name for the sale screen picker:
create index idx_products_name_lower on products(org_id, lower(name));

comment on column products.unit_price is
    'The price the product sells for TODAY. Historical prices live on sale_items.';


-- ------------------------------------------------------------- customers --
create table customers (
    id          uuid primary key default gen_random_uuid(),
    org_id      uuid        not null references organisations(id) on delete cascade,
    full_name   text        not null check (length(trim(full_name)) > 0),
    phone       text,
    email       text,
    address     text,
    created_at  timestamptz not null default now(),
    constraint uq_customer_phone_per_org unique (org_id, phone)
);

create index idx_customers_org on customers(org_id);


-- ----------------------------------------------------------------- sales --
create table sales (
    id             uuid primary key default gen_random_uuid(),
    org_id         uuid        not null references organisations(id) on delete cascade,
    reference      text        not null,                -- human readable: SA-2026-0041
    customer_id    uuid        references customers(id) on delete set null,  -- NULL = walk-in
    sold_by        uuid        references profiles(id)  on delete set null,
    status         sale_status    not null default 'draft',
    payment_method payment_method not null default 'cash',
    note           text,
    sold_at        timestamptz not null default now(),
    constraint uq_sale_reference_per_org unique (org_id, reference)
);

create index idx_sales_org_date on sales(org_id, sold_at desc);
create index idx_sales_customer on sales(customer_id);

comment on column sales.customer_id is
    'Nullable on purpose: a walk-in sale has no customer. The relationship is
     OPTIONAL one-to-many (one customer to many sales).';


-- ------------------------------------------------------------ sale_items --
-- THE JUNCTION TABLE.
-- A sale contains many products; a product appears in many sales. That is a
-- many-to-many relationship, which a relational database cannot store directly.
-- It is resolved into two one-to-many relationships through this table, which
-- also carries its own attributes (quantity, unit_price).
create table sale_items (
    id          uuid primary key default gen_random_uuid(),
    sale_id     uuid        not null references sales(id)    on delete cascade,
    product_id  uuid        not null references products(id) on delete restrict,
    quantity    integer     not null check (quantity > 0),
    unit_price  numeric(12,2) not null check (unit_price >= 0),
    -- Generated column: maintained by PostgreSQL, impossible to desynchronise.
    line_total  numeric(12,2) generated always as (quantity * unit_price) stored,
    -- The same product may not appear twice on one sale; increase the quantity.
    -- (sale_id, product_id) is therefore a candidate key of this table.
    constraint uq_product_per_sale unique (sale_id, product_id)
);

create index idx_sale_items_sale    on sale_items(sale_id);
create index idx_sale_items_product on sale_items(product_id);

comment on column sale_items.unit_price is
    'HISTORICAL SNAPSHOT. This is what the customer actually paid on that day.
     It is not a copy of products.unit_price - it is a different fact that
     happens to share the value at the moment of sale. Storing it is what makes
     old receipts reproducible after a price change.';


-- ------------------------------------------------------- stock movements --
-- The stock ledger. Current stock is DERIVED from this table (see v_product_stock),
-- never stored on products. Append-only: every change is explained and attributed.
create table stock_movements (
    id             uuid primary key default gen_random_uuid(),
    org_id         uuid        not null references organisations(id) on delete cascade,
    product_id     uuid        not null references products(id) on delete restrict,
    sale_id        uuid        references sales(id) on delete set null,  -- set when caused by a sale
    movement_type  movement_type not null,
    quantity       integer     not null,
    reason         text,
    created_by     uuid        references profiles(id) on delete set null,
    created_at     timestamptz not null default now(),

    -- 'in' and 'out' quantities are always positive magnitudes.
    -- 'adjustment' may be signed (e.g. -3 for breakage, +2 for a recount).
    constraint chk_movement_quantity check (
        (movement_type in ('in','out') and quantity > 0)
        or (movement_type = 'adjustment' and quantity <> 0)
    )
);

create index idx_movements_product on stock_movements(product_id, created_at desc);
create index idx_movements_org     on stock_movements(org_id, created_at desc);

