-- ============================================================================
-- OJA baseline, chunk 03 of 08: Helper functions and the updated_at trigger
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 196-238).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 3. HELPER FUNCTIONS
-- ============================================================================

-- Returns the organisation of the currently authenticated user.
-- SECURITY DEFINER so that reading profiles inside a policy does not itself
-- trigger the policy on profiles (which would recurse).
create or replace function current_org_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $fn_current_org_id$
    select org_id from public.profiles where id = auth.uid();
$fn_current_org_id$;

create or replace function current_user_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $fn_current_user_role$
    select role from public.profiles where id = auth.uid();
$fn_current_user_role$;

-- Keeps products.updated_at honest.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $fn_set_updated_at$
begin
    new.updated_at := now();
    return new;
end;
$fn_set_updated_at$;

create trigger trg_products_updated_at
    before update on products
    for each row execute function set_updated_at();

