-- ============================================================================
-- OJA baseline, chunk 04 of 08: Derived data: the four views
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 239-306).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 4. DERIVED DATA (VIEWS)
-- ============================================================================

-- Current stock per product = sum of the ledger.
--   in         -> +quantity
--   out        -> -quantity
--   adjustment -> +quantity (already signed)
create or replace view v_product_stock as
select
    p.id            as product_id,
    p.org_id,
    p.sku,
    p.name,
    p.category_id,
    p.unit_price,
    p.cost_price,
    p.reorder_level,
    p.is_active,
    coalesce(sum(
        case m.movement_type
            when 'in'         then  m.quantity
            when 'out'        then -m.quantity
            when 'adjustment' then  m.quantity
        end
    ), 0)::integer as stock_quantity
from products p
left join stock_movements m on m.product_id = p.id
group by p.id;

-- Products at or below their reorder level.
create or replace view v_low_stock as
select *
from v_product_stock
where is_active
  and stock_quantity <= reorder_level;

-- Revenue per day (completed sales only).
create or replace view v_daily_sales as
select
    s.org_id,
    (s.sold_at at time zone 'Africa/Lagos')::date as sale_date,
    count(distinct s.id)        as sale_count,
    coalesce(sum(si.quantity), 0) as units_sold,
    coalesce(sum(si.line_total), 0)::numeric(14,2) as revenue
from sales s
join sale_items si on si.sale_id = s.id
where s.status = 'completed'
group by s.org_id, (s.sold_at at time zone 'Africa/Lagos')::date;

-- Sale header with its computed total.
create or replace view v_sale_totals as
select
    s.id as sale_id,
    s.org_id,
    s.reference,
    s.status,
    s.payment_method,
    s.sold_at,
    s.customer_id,
    s.sold_by,
    coalesce(sum(si.line_total), 0)::numeric(14,2) as total_amount,
    coalesce(sum(si.quantity), 0) as item_count
from sales s
left join sale_items si on si.sale_id = s.id
group by s.id;

