-- ============================================================================
-- OJA baseline, chunk 05 of 08: complete_sale()
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 307-354).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 5. BUSINESS RULES ENFORCED IN THE DATABASE
-- ============================================================================

-- 5.1 Completing a sale writes one 'out' movement per line and refuses to
--     oversell. Running it inside one function makes it ATOMIC: either every
--     line is deducted or nothing happens at all.
create or replace function complete_sale(p_sale_id uuid)
returns void
language plpgsql
security invoker            -- still subject to RLS: you cannot touch another org
as $fn_complete_sale$
declare
    item        record;
    available   integer;
    v_org       uuid;
begin
    select org_id into v_org from sales where id = p_sale_id and status = 'draft';
    if v_org is null then
        raise exception 'Sale % not found or is not a draft', p_sale_id;
    end if;

    for item in
        select product_id, quantity from sale_items where sale_id = p_sale_id
    loop
        select stock_quantity into available
        from v_product_stock where product_id = item.product_id;

        if available < item.quantity then
            raise exception
                'Insufficient stock for product %: % requested, % available',
                item.product_id, item.quantity, available;
        end if;

        insert into stock_movements
            (org_id, product_id, sale_id, movement_type, quantity, reason, created_by)
        values
            (v_org, item.product_id, p_sale_id, 'out', item.quantity, 'Sale', auth.uid());
    end loop;

    update sales
       set status = 'completed', sold_at = now()
     where id = p_sale_id;
end;
$fn_complete_sale$;


