-- ============================================================================
-- OJA baseline, chunk 06 of 08: void_sale()
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 355-389).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================

-- 5.2 Voiding a sale never deletes anything. It writes COMPENSATING movements
--     so the ledger still explains itself, and flips the status.
create or replace function void_sale(p_sale_id uuid, p_reason text)
returns void
language plpgsql
security invoker
as $fn_void_sale$
declare
    item  record;
    v_org uuid;
begin
    select org_id into v_org from sales where id = p_sale_id and status = 'completed';
    if v_org is null then
        raise exception 'Sale % not found or is not completed', p_sale_id;
    end if;

    if current_user_role() not in ('owner','manager') then
        raise exception 'Only an owner or manager may void a sale';
    end if;

    for item in
        select product_id, quantity from sale_items where sale_id = p_sale_id
    loop
        insert into stock_movements
            (org_id, product_id, sale_id, movement_type, quantity, reason, created_by)
        values
            (v_org, item.product_id, p_sale_id, 'in', item.quantity,
             coalesce('Void: ' || p_reason, 'Void'), auth.uid());
    end loop;

    update sales set status = 'void', note = coalesce(p_reason, note) where id = p_sale_id;
end;
$fn_void_sale$;


