-- ============================================================================
-- OJA baseline, chunk 07 of 08: next_sale_reference()
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 390-402).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================

-- 5.3 Generate the next human-readable sale reference for an organisation.
create or replace function next_sale_reference(p_org_id uuid)
returns text
language sql
stable
as $fn_next_sale_reference$
    select 'SA-' || to_char(now(), 'YYYY') || '-' ||
           lpad((count(*) + 1)::text, 4, '0')
    from sales
    where org_id = p_org_id
      and date_part('year', sold_at) = date_part('year', now());
$fn_next_sale_reference$;

