-- ============================================================================
-- OJA baseline, chunk 08 of 08: Enable RLS and create every policy
--
-- Generated from supabase/migrations/0001_initial_schema.sql (lines 403-489).
-- This is a PASTE AID, not a migration. The committed baseline remains the
-- single source of truth; do not edit this file, edit the baseline and
-- regenerate. Run chunks strictly in order, confirming each before the next.
-- ============================================================================


-- ============================================================================
-- 6. ROW LEVEL SECURITY
--    Authorisation lives in the DATABASE. Even if the front end is bypassed
--    entirely, a user cannot read or write another organisation's rows.
-- ============================================================================

alter table organisations   enable row level security;
alter table profiles        enable row level security;
alter table categories      enable row level security;
alter table products        enable row level security;
alter table customers       enable row level security;
alter table sales           enable row level security;
alter table sale_items      enable row level security;
alter table stock_movements enable row level security;

-- ---- organisations -------------------------------------------------------
create policy org_select on organisations
    for select using (id = current_org_id());

create policy org_update on organisations
    for update using (id = current_org_id() and current_user_role() = 'owner');

-- ---- profiles ------------------------------------------------------------
create policy profiles_select on profiles
    for select using (org_id = current_org_id());

-- A user may edit their own name, but NOT their own role (no self-promotion).
create policy profiles_update_self on profiles
    for update using (id = auth.uid())
    with check (id = auth.uid() and role = (select role from profiles where id = auth.uid()));

create policy profiles_update_by_owner on profiles
    for update using (org_id = current_org_id() and current_user_role() = 'owner');

-- ---- categories / products / customers ----------------------------------
create policy categories_all on categories
    for all using (org_id = current_org_id())
    with check (org_id = current_org_id());

create policy products_select on products
    for select using (org_id = current_org_id());

create policy products_write on products
    for all using (org_id = current_org_id() and current_user_role() in ('owner','manager'))
    with check (org_id = current_org_id() and current_user_role() in ('owner','manager'));

create policy customers_all on customers
    for all using (org_id = current_org_id())
    with check (org_id = current_org_id());

-- ---- sales ---------------------------------------------------------------
create policy sales_select on sales
    for select using (org_id = current_org_id());

create policy sales_insert on sales
    for insert with check (org_id = current_org_id());

create policy sales_update on sales
    for update using (org_id = current_org_id());

-- ---- sale_items ----------------------------------------------------------
-- This table has no org_id of its own, so the policy reaches through its parent.
-- Trade-off: one extra sub-query per row versus denormalising org_id onto the
-- junction table. At MVP scale, correctness wins; the index on sales(id) keeps
-- the lookup cheap.
create policy sale_items_all on sale_items
    for all using (
        exists (select 1 from sales s
                 where s.id = sale_items.sale_id and s.org_id = current_org_id())
    )
    with check (
        exists (select 1 from sales s
                 where s.id = sale_items.sale_id and s.org_id = current_org_id())
    );

-- ---- stock_movements -----------------------------------------------------
create policy movements_select on stock_movements
    for select using (org_id = current_org_id());

-- Only managers and owners may manually move stock. Sale-driven movements are
-- written by complete_sale(), which runs as the calling user and passes this too.
create policy movements_insert on stock_movements
    for insert with check (org_id = current_org_id());

-- Deliberately NO update/delete policy: the ledger is append-only.

