import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/types/database.types";

// The signed-in user's profile, with the organisation it belongs to.
//
// Row types come from types/database.types.ts, generated by
//   npx supabase gen types typescript --project-id <ref> > types/database.types.ts
// and never hand-written (02_CLAUDE.md section 5.4). The Supabase client is
// parameterised with Database in lib/supabase/server.ts, so the shape of the
// select below - including the nested organisations object - is inferred from
// the real schema rather than asserted.

type UserRole = Database["public"]["Enums"]["user_role"];

export interface CurrentProfile {
  id: string;
  fullName: string;
  role: UserRole;
  isActive: boolean;
  organisation: {
    id: string;
    name: string;
    currency: string;
  };
}

export async function getCurrentProfile(
  userId: string
): Promise<CurrentProfile | null> {
  const supabase = await createClient();

  // Named columns only; no SELECT * (section 5.1). Selecting through the
  // org_id foreign key nests the related row as an OBJECT rather than
  // flattening it into the parent - the trap listed in section 8.
  const { data, error } = await supabase
    .from("profiles")
    .select("id, full_name, role, is_active, organisations ( id, name, currency )")
    .eq("id", userId)
    .maybeSingle();

  if (error) {
    // RLS returning no rows is not an error, so reaching here means something
    // genuinely failed. Logged server-side, never surfaced to the user.
    console.error("[queries.getCurrentProfile]", error.message);
    return null;
  }

  // No row means the auth user has no profile yet, which is the state a brand
  // new sign-up is in until onboarding creates one. Not an error.
  if (!data || !data.organisations) {
    return null;
  }

  return {
    id: data.id,
    fullName: data.full_name,
    role: data.role,
    isActive: data.is_active,
    organisation: {
      id: data.organisations.id,
      name: data.organisations.name,
      currency: data.organisations.currency,
    },
  };
}

// Convenience for Server Components and Server Actions that need the signed-in
// user's profile and do not already hold the user id. Verifies the token rather
// than reading the cookie, the same way the shell guard does.
export async function getSignedInProfile(): Promise<CurrentProfile | null> {
  const supabase = await createClient();

  const { data } = await supabase.auth.getClaims();
  const userId = data?.claims?.sub;

  if (typeof userId !== "string") {
    return null;
  }

  return getCurrentProfile(userId);
}

// PRD section 9.2: creating and editing products, receiving stock and making
// adjustments are owner and manager only. Staff read inventory, because they
// need prices at the till.
//
// This is the UI half of the rule. The database half is migration 0003, which
// restricts direct stock_movements inserts to the same two roles. Section 9.1
// principle 3: hiding a button is not access control, so both exist.
export function canManageInventory(role: CurrentProfile["role"]): boolean {
  return role === "owner" || role === "manager";
}
